"""
Custom parser for OSU benchmark with bash time command output.
Parses the 'real' time from bash time command output in stderr.
"""
import re
from pathlib import Path


def parse_osu_time(job_id: int, path: Path = Path.cwd()) -> float:
    """
    Parse execution time from the stderr file generated by bash time command.
    
    Args:
        job_id: The Slurm job ID
        path: The path where to look for the slurm output
        
    Returns:
        Execution time in seconds
    """
    # Find the stderr file
    stderr_file = path / f"slurm-{job_id}.err"
    
    if not stderr_file.exists():
        stderr_file = Path(f"slurm-{job_id}.err")
    
    if not stderr_file.exists():
        print(f"Warning: stderr file for job {job_id} not found at {stderr_file}")
        return float('inf')
    
    content = stderr_file.read_text()
    
    # Parse bash time format: real    2m53.933s
    match = re.search(r'real\s+(\d+)m([\d.]+)s', content)
    if match:
        minutes = int(match.group(1))
        seconds = float(match.group(2))
        total_seconds = minutes * 60 + seconds
        print(f"Parsed time for job {job_id}: {total_seconds}s")
        return total_seconds
    
    # Try alternative format: real 173.933
    match = re.search(r'real\s+([\d.]+)', content)
    if match:
        total_seconds = float(match.group(1))
        print(f"Parsed time for job {job_id}: {total_seconds}s")
        return total_seconds
    
    print(f"Warning: Could not parse time from {stderr_file}, content: {content[:200]}")
    return float('inf')
