"""This module contains functions to perform the parsing of a slurm output
generated by the OSU benchmark.
"""
from pathlib import Path


def parse_osu_output(job_id: str, path: Path = Path.cwd()) -> float:
    """Performs the parsing of the file slurm-{job_id}.out by returning
    the sums of the elapsed time multiplied by the size of the messages.

    Args:
        out_file (str): The job slurm output file path to parse.
        path (Path): The path where to look for the slurm output.
            Defaults to the current working directory.

    Returns:
        float: The time elapsed by the application, in milliseconds.
    """
    elapsed_time = 0
    out_file = path / f"slurm-{job_id}.out"
    try:
        with open(out_file, "r") as file:
            lines = file.readlines()
            for line in lines:
                split_line = line.split()
                if split_line:
                    try:
                        size, latency = float(
                            split_line[0]), float(
                            split_line[1])
                        elapsed_time += size * latency
                    except ValueError:
                        continue
            return elapsed_time
    except FileNotFoundError:
        raise FileNotFoundError("Slurm output was not generated.")


def parse_osu_output_1024(job_id: str, path: Path = Path.cwd()) -> float:
    """Performs the parsing of the file slurm-{job_id}.out by returning
    the elapsed time.

    Args:
        out_file (str): The job slurm output file path to parse.
        path (Path): The path where to look for the slurm output.
            Defaults to the current working directory.

    Returns:
        float: The time elapsed by the application, in milliseconds.
    """
    elapsed_time = 0
    out_file = path / f"slurm-{job_id}.out"
    try:
        with open(out_file, "r") as file:
            lines = file.readlines()
            for line in lines:
                split_line = line.split()
                if split_line:
                    try:
                        size, latency = float(
                            split_line[0]), float(
                            split_line[1])
                        if size == 1024:
                            return latency
                    except ValueError:
                        continue
            return elapsed_time
    except FileNotFoundError:
        raise FileNotFoundError("Slurm output was not generated.")


def parse_osu_output_8(job_id: str, path: Path = Path.cwd()) -> float:
    """Performs the parsing of the file slurm-{job_id}.out by returning
    the elapsed time.

    Args:
        out_file (str): The job slurm output file path to parse.
        path (Path): The path where to look for the slurm output.
            Defaults to the current working directory.

    Returns:
        float: The time elapsed by the application, in milliseconds.
    """
    elapsed_time = 0
    out_file = path / f"slurm-{job_id}.out"
    try:
        with open(out_file, "r") as file:
            lines = file.readlines()
            for line in lines:
                split_line = line.split()
                if split_line:
                    try:
                        size, latency = float(
                            split_line[0]), float(
                            split_line[1])
                        if size == 8:
                            return latency
                    except ValueError:
                        continue
            return elapsed_time
    except FileNotFoundError:
        raise FileNotFoundError("Slurm output was not generated.")


def parse_osu_output_1048576(job_id: str, path: Path = Path.cwd()) -> float:
    """Performs the parsing of the file slurm-{job_id}.out by returning
    the elapsed time.

    Args:
        out_file (str): The job slurm output file path to parse.
        path (Path): The path where to look for the slurm output.
            Defaults to the current working directory.

    Returns:
        float: The time elapsed by the application, in milliseconds.
    """
    elapsed_time = 0
    out_file = path / f"slurm-{job_id}.out"
    try:
        with open(out_file, "r") as file:
            lines = file.readlines()
            for line in lines:
                split_line = line.split()
                if split_line:
                    try:
                        size, latency = float(
                            split_line[0]), float(
                            split_line[1])
                        if size == 1048576:
                            return latency
                    except ValueError:
                        continue
            return elapsed_time
    except FileNotFoundError:
        raise FileNotFoundError("Slurm output was not generated.")


def parse_osu_output_268435456(job_id: str, path: Path = Path.cwd()) -> float:
    """Performs the parsing of the file slurm-{job_id}.out by returning
    the elapsed time for 256MB message size.

    Args:
        out_file (str): The job slurm output file path to parse.
        path (Path): The path where to look for the slurm output.
            Defaults to the current working directory.

    Returns:
        float: The time elapsed by the application, in microseconds.
    """
    elapsed_time = 0
    out_file = path / f"slurm-{job_id}.out"
    try:
        with open(out_file, "r") as file:
            lines = file.readlines()
            for line in lines:
                split_line = line.split()
                if split_line:
                    try:
                        size, latency = float(
                            split_line[0]), float(
                            split_line[1])
                        if size == 268435456:
                            return latency
                    except ValueError:
                        continue
            return elapsed_time
    except FileNotFoundError:
        raise FileNotFoundError("Slurm output was not generated.")


def parse_osu_output_latency_sum(job_id: str, path: Path = Path.cwd()) -> float:
    """Performs the parsing of the file slurm-{job_id}.out by returning
    the sum of all latencies across all message sizes.

    Args:
        job_id (str): The job slurm output file path to parse.
        path (Path): The path where to look for the slurm output.
            Defaults to the current working directory.

    Returns:
        float: The sum of all latencies, in microseconds.
    """
    total_latency = 0.0
    out_file = path / f"slurm-{job_id}.out"
    try:
        with open(out_file, "r") as file:
            lines = file.readlines()
            for line in lines:
                line = line.strip()
                # Skip empty lines, comments, and non-data lines
                if not line or line.startswith('#') or not line[0].isdigit():
                    continue
                split_line = line.split()
                if len(split_line) >= 2:
                    try:
                        total_latency += float(split_line[1])
                    except ValueError:
                        continue
            return total_latency
    except FileNotFoundError:
        raise FileNotFoundError("Slurm output was not generated.")


def parse_osu_output_latency_sum_node3(job_id: str, path: Path = None) -> float:
    """Node3-specific parser - looks in slurm_outputs subdirectory."""
    if path is None:
        path = Path("slurm_outputs")
    return parse_osu_output_latency_sum(job_id, path)


def parse_osu_output_latency_sum_node4(job_id: str, path: Path = None) -> float:
    """Node4-specific parser - looks in slurm_outputs subdirectory."""
    if path is None:
        path = Path("slurm_outputs")
    return parse_osu_output_latency_sum(job_id, path)


def parse_osu_output_latency_sum_node1(job_id: str, path: Path = None) -> float:
    """Node1-specific parser - looks in slurm_outputs subdirectory."""
    if path is None:
        path = Path("slurm_outputs")
    return parse_osu_output_latency_sum(job_id, path)


def parse_osu_output_latency_sum_node2(job_id: str, path: Path = None) -> float:
    """Node2-specific parser - looks in slurm_outputs subdirectory."""
    if path is None:
        path = Path("slurm_outputs")
    return parse_osu_output_latency_sum(job_id, path)

